app.name=undongpedia
app.version=1.0


server.port=9090
server.context-path=/undongpedia


logging.level.root=INFO
logging.level.org.tlmr=DEBUG

# Application Base URL
app.baseUrl=http://13.124.190.205:80/undongpedia

queue.activation.threshold=5
queue.scheduler.interval=5000
queue.max.concurrent.courses=50
queue.websocket.throttle.ms=500
queue.max.queue.size=2000
