app.name=undongpedia
app.version=1.0


server.port=9090
server.context-path=/undongpedia


logging.level.root=INFO
logging.level.org.tlmr=DEBUG

# Application Base URL
app.baseUrl=http://localhost:9090/undongpedia

# 🔥 대기열 활성화 임계값을 낮춤 (모달창 테스트용)
queue.activation.threshold=1
queue.scheduler.interval=600000
queue.max.concurrent.courses=50
queue.websocket.throttle.ms=500
queue.max.queue.size=2000
